site_name: Arvanis Game Wiki
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.highlight
    - search.share
    - announce.dismiss
    - navigation.footer
  palette:
    scheme: slate
    primary: purple
    accent: light blue
  font:
    text: Quicksand
  language: en
extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  copyright: Copyright &copy; 2024 Jake Cylkowski - All Rights Reserved - No reusage or duplication without explicit written permission.
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - tables
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - md_in_html
plugins:
  - glightbox

